using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Watsonia.AusPostInterface
{
	/// <summary>
	/// An item element to be supplied for each parcel.
	/// </summary>
	/// <seealso cref="Watsonia.AusPostInterface.ApiItem" />
	public sealed class Item : ApiItem
	{
		/// <summary>
		/// The identifier for the item previously generated by Australia Post during a Create Shipments API call. You specify this field to make changes to an existing item. If you don't specify this field, then a new item is created and added to the shipment.
		/// </summary>
		/// <value>
		/// The item identifier.
		/// </value>
		[StringLength(50)]
		public string ItemID { get; set; }

		/// <summary>
		/// A unique reference for the item, generated by the merchant. This value must be unique across all items for the charge account. 
		/// </summary>
		/// <value>
		/// The item reference.
		/// </value>
		[StringLength(50)]
		public string ItemReference { get; set; }

		/// <summary>
		/// The Australia Post code representing the postage product for the item.
		/// </summary>
		/// <value>
		/// The product identifier.
		/// </value>
		[Required]
		[StringLength(5)]
		public string ProductID { get; set; }

		/// <summary>
		/// A description of the item, generated by the merchant.
		/// </summary>
		/// <value>
		/// The item description.
		/// </value>
		public string ItemDescription { get; set; }

		/// <summary>
		/// The length of the parcel in centimetres. If volumetric pricing applied then this is mandatory. 
		/// </summary>
		/// <value>
		/// The length.
		/// </value>
		public decimal Length { get; set; }

		/// <summary>
		/// The width of the parcel in centimetres. If volumetric pricing applied then this is mandatory. 
		/// </summary>
		/// <value>
		/// The width.
		/// </value>
		public decimal Width { get; set; }

		/// <summary>
		/// The height of the parcel in centimetres. If volumetric pricing applied then this is mandatory. 
		/// </summary>
		/// <value>
		/// The height.
		/// </value>
		public decimal Height { get; set; }

		/// <summary>
		/// The parcel's weight in kilograms. This is mandatory for normal shipments (movement_type = DESPATCH) but must not be specified for returns shipments (movement_type = RETURN).
		/// </summary>
		/// <value>
		/// The weight.
		/// </value>
		[Required]
		public decimal Weight { get; set; }

		/// <summary>
		/// Whether the item contains dangerous goods, generated by the merchant.
		/// </summary>
		/// <value>
		/// The contains dangerous goods.
		/// </value>
		public bool? ContainsDangerousGoods { get; set; }

		/// <summary>
		/// Whether the item can be left in a safe place on delivery without receiving a signature. This is optional for domestic shipments (and defaults to true), but must not be specified for international shipments. 
		/// </summary>
		/// <value>
		/// The authority to leave.
		/// </value>
		public bool? AuthorityToLeave { get; set; }

		/// <summary>
		/// Whether items can be delivered to their final destination as they become available or whether all items in the resulting consignment must be delivered together.
		/// </summary>
		/// <value>
		/// The allow partial delivery.
		/// </value>
		public bool? AllowPartialDelivery { get; set; }

		/// <summary>
		/// The packaging type for this item. Some example values are: CTN, PAL, SAT, BAG, ENV, ITM, JIF, SKI.
		/// </summary>
		/// <remarks>
		/// Note, for StarTrack products, the packaging type (refereed to as a unit type by StarTrack) is mandatory and has a maximum length of 3. 
		/// </remarks>
		/// <value>
		/// The type of the packaging.
		/// </value>
		[StringLength(3)]
		public string PackagingType { get; set; }

		/// <summary>
		/// Authority to Leave (ATL) authorisation code. If this field is provided, it must begin with C and be followed by a 9 digit number. 
		/// </summary>
		/// <value>
		/// The authority to leave number.
		/// </value>
		[StringLength(10)]
		[JsonProperty("atl_number")]
		public string AuthorityToLeaveNumber { get; set; }

		/// <summary>
		/// Whether your customer can request that the item be left in a safe place at the delivery address if they are not home to sign for their delivery. Your customer can request this while the item is on its way. This field is optional for domestic shipments (and defaults to true), but must not be specified for international shipments. This field works with the AuthorityToLeave field. If the AuthorityToLeave field is set to true, the SafeDropEnabled field is ignored. Please review the fact sheet for full details. 
		/// </summary>
		/// <value>
		/// Whether safe drop is enabled.
		/// </value>
		public bool? SafeDropEnabled { get; set; }

		/// <summary>
		/// Additional features for the item.
		/// </summary>
		/// <value>
		/// The features.
		/// </value>
		public Dictionary<string, ItemFeature> Features { get; set; } = new Dictionary<string, ItemFeature>();

		// TODO: Features

		// TODO: Tracking details

		// TODO: Other fields

		/// <summary>
		/// Use this field to include any additional comments on the label.
		/// </summary>
		/// <value>
		/// The comments.
		/// </value>
		[StringLength(120)]
		public string Comments { get; set; }

		// TODO: Item contents

		/// <summary>
		/// Loads a Item from a JSON string.
		/// </summary>
		/// <param name="json">The json.</param>
		public static Item FromJson(string json)
		{
			var serializer = new ApiSerializer();
			return serializer.FromJson<Item>(json);
		}
	}
}
